# Generated by Django 4.0.2 on 2022-11-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classArm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='className',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
