# Generated by Django 4.0.2 on 2022-11-05 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0002_classarmteacher'),
        ('users', '0004_remove_user_classarm_remove_user_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='result.section'),
        ),
    ]
